// packages/react-perf/scripts/generate-assets.ts
#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import pc from 'picocolors'

import { ICON_RENAMES } from '../../core/src/utils.ts'
import type { SvgMap } from './utils'
import {
    ICONS_PATH,
    INDEX_PATH,
    readSvgsFromDisk,
    toPascalCase,
    verifyIcons,
    WEIGHTS,
} from './utils'

// Create a reverse mapping for aliases (Correction -> [Typos])
const ICON_ALIASES: Record<string, string[]> = {}
for (const [typo, correction] of Object.entries(ICON_RENAMES)) {
    if (!ICON_ALIASES[correction]) {
        ICON_ALIASES[correction] = []
    }
    ICON_ALIASES[correction].push(typo)
}

// --- Types ---

interface Icon {
    category: string
    style: string
    name: string // kebab-case (e.g. arrow-left)
    pascalName: string // PascalCase (e.g. ArrowLeft)
    globalName: string // Disambiguated Name (e.g. ArrowLeftBold)
    jsx: string
    preview: string
}

interface FileDefinition {
    path: string
    content: string
}

// --- Helpers ---

/**
 * Flattens the nested SvgMap into a list of Icon objects for easier processing.
 */
function getIcons(map: SvgMap): Icon[] {
    const icons: Icon[] = []
    for (const [category, styles] of Object.entries(map)) {
        for (const [style, names] of Object.entries(styles)) {
            for (const [name, data] of Object.entries(names)) {
                icons.push({
                    category,
                    style,
                    name,
                    pascalName: toPascalCase(name),
                    globalName: toPascalCase(`${name}-${style}`),
                    jsx: data.jsx,
                    preview: data.preview,
                })
            }
        }
    }
    return icons
}

/**
 * Utility to group icons by a specific key.
 */
function groupBy<T>(array: T[], keySelector: (item: T) => string): Record<string, T[]> {
    return array.reduce(
        (acc, item) => {
            const key = keySelector(item)
            if (!acc[key]) acc[key] = []
            acc[key].push(item)
            return acc
        },
        {} as Record<string, T[]>
    )
}

/**
 * Returns a list of aliases (typos) for a given icon name, including partial matches.
 */
function getAliasesForIcon(name: string): string[] {
    const aliases = new Set<string>()
    // Exact matches
    if (ICON_ALIASES[name]) {
        ICON_ALIASES[name].forEach(a => aliases.add(a))
    }
    // Partial matches
    Object.entries(ICON_ALIASES).forEach(([correct, typos]) => {
        if (name.includes(correct) && name !== correct) {
            typos.forEach(typo => {
                if (/[^a-z0-9]/i.test(typo)) return
                aliases.add(name.replace(correct, typo))
            })
        }
    })
    return Array.from(aliases).filter(a => a !== name)
}

// --- Generators ---

const Generators = {
    /**
     * Generates the React component for a single icon.
     */
    component: (icon: Icon): FileDefinition => {
        const content = `/* GENERATED FILE */
import React from "react"
import { forwardRef } from "react"
import IconBase from "../../../lib/IconBase"
import type { IconProps, Icon } from "../../../lib/types"

/**
 * ![img](data:image/svg+xml;base64,${icon.preview})
 */
export const ${icon.pascalName}: Icon = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
    <IconBase ref={ref} {...props}>
        ${icon.jsx.trim()}
    </IconBase>
))

${icon.pascalName}.displayName = "${icon.pascalName}"
`
        return {
            path: path.join(ICONS_PATH, icon.category, icon.style, `${icon.pascalName}.tsx`),
            content,
        }
    },

    aliasComponent: (icon: Icon, alias: string): FileDefinition => {
        const content = `/* GENERATED FILE */
import { ${icon.pascalName} } from './${icon.pascalName}'
import type { Icon } from '../../../lib/types'

/**
 * @deprecated Use ${icon.pascalName} instead
 */
export const ${alias}: Icon = ${icon.pascalName}
`
        return {
            path: path.join(ICONS_PATH, icon.category, icon.style, `${alias}.tsx`),
            content,
        }
    },

    /**
     * Generates the index.ts for a specific style (e.g. icons/essentials/bold.ts).
     * Uses named exports instead of `export *`.
     * NOTE: Placed as a sibling to the style folder to support "clean" imports.
     */
    styleIndex: (style: string, icons: Icon[], folderPath: string): FileDefinition => {
        // folderPath is .../category/style
        // We want .../category/style.ts
        const parentDir = path.dirname(folderPath)

        let exports = icons
            .map(icon => `export { ${icon.pascalName} } from './${style}/${icon.pascalName}';`)
            .sort()
            .join('\n')

        // Add deprecated aliases
        icons.forEach(icon => {
            const aliases = getAliasesForIcon(icon.pascalName)
            aliases.forEach(alias => {
                exports += `\nexport { ${alias} } from './${style}/${alias}';`
            })
        })

        return {
            path: path.join(parentDir, `${style}.ts`),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the styled.ts for a specific style (e.g. icons/essentials/bold/styled.ts).
     * Exports icons with their global unique names.
     */
    styleGlobalIndex: (style: string, icons: Icon[], folderPath: string): FileDefinition => {
        const exports = icons
            .map(
                icon =>
                    `export { ${icon.pascalName} as ${icon.globalName} } from './${icon.pascalName}';`
            )
            .sort()
            .join('\n')

        return {
            path: path.join(folderPath, 'styled.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the index.ts for a category (e.g. icons/essentials.ts).
     * Exports styles as namespaces.
     * NOTE: Placed as a sibling to the category folder.
     */
    categoryIndex: (category: string, styles: string[], folderPath: string): FileDefinition => {
        // folderPath is .../icons/category
        // We want .../icons/category.ts
        const parentDir = path.dirname(folderPath)

        const exports = styles
            .map(style => `export * as ${style} from './${category}/${style}';`)
            .sort()
            .join('\n')

        return {
            path: path.join(parentDir, `${category}.ts`),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the styled.ts for a category (e.g. icons/essentials/styled.ts).
     * Exports everything from each style's styled.ts.
     */
    categoryGlobalIndex: (
        category: string,
        styles: string[],
        folderPath: string
    ): FileDefinition => {
        const exports = styles
            .map(style => `export * from './${style}/styled';`)
            .sort()
            .join('\n')

        return {
            path: path.join(folderPath, 'styled.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the root index.ts (src/icons/index.ts).
     */
    rootIndex: (categories: string[]): FileDefinition => {
        const exports = categories
            .map(category => `export * as ${toPascalCase(category)} from './${category}';`)
            .sort()
            .join('\n')

        return {
            path: path.join(ICONS_PATH, 'index.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the root styled.ts (src/icons/styled.ts).
     */
    rootGlobalIndex: (categories: string[]): FileDefinition => {
        const exports = categories
            .map(category => `export * from './${category}/styled';`)
            .sort()
            .join('\n')

        return {
            path: path.join(ICONS_PATH, 'styled.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates grouped indexes by weight (e.g. src/icons/style/Bold.ts).
     */
    weightIndexes: (icons: Icon[]): FileDefinition[] => {
        const files: FileDefinition[] = []
        const byStyle = groupBy(icons, i => i.style)

        for (const weight of WEIGHTS) {
            const iconsForWeight = byStyle[weight] || []

            // Explicitly export each icon found in this weight to avoid "export *"
            // We export directly from the component file to be tree-shake friendly
            let content = iconsForWeight
                .sort((a, b) => a.pascalName.localeCompare(b.pascalName))
                .map(
                    icon =>
                        `export { ${icon.pascalName} } from '../${icon.category}/${icon.style}/${icon.pascalName}';`
                )
                .join('\n')

            // Add aliases to weight indexes too!
            iconsForWeight.forEach(icon => {
                const aliases = getAliasesForIcon(icon.pascalName)
                aliases.forEach(alias => {
                    content += `\nexport { ${alias} } from '../${icon.category}/${icon.style}/${alias}';`
                })
            })

            files.push({
                path: path.join(ICONS_PATH, 'style', `${weight}.ts`),
                content: content ? `${content}\n` : '',
            })
        }
        return files
    },

    /**
     * Generates the index for styles directory (src/icons/style/index.ts).
     */
    stylesIndex: (): FileDefinition => {
        const content = WEIGHTS.map(weight => `export * as ${weight} from './${weight}';`).join(
            '\n'
        )

        return {
            path: path.join(ICONS_PATH, 'style', 'index.ts'),
            content: `${content}\n`,
        }
    },

    /**
     * Generates the main entry point (src/index.ts).
     */
    mainEntry: (): FileDefinition => {
        const content = `/* GENERATED FILE */
export type { IconProps } from "./lib"
export { IconBase } from "./lib"
export * from "./icons/styled"
import * as solar from "./icons"
export { solar }
`
        return {
            path: INDEX_PATH,
            content,
        }
    },
}

// --- Stages ---

function clean() {
    const pathsToClean = [ICONS_PATH, INDEX_PATH]
    pathsToClean.forEach(p => {
        if (fs.existsSync(p)) {
            fs.rmSync(p, { recursive: true, force: true })
            console.log(pc.blue(`Removed ${p}`))
        }
    })
}

function generate(icons: Icon[]) {
    const files: FileDefinition[] = []

    // 1. Icon Components & Style Indexes
    const byCategory = groupBy(icons, i => i.category)

    for (const [category, catIcons] of Object.entries(byCategory)) {
        const byStyle = groupBy(catIcons, i => i.style)

        for (const [style, styleIcons] of Object.entries(byStyle)) {
            const stylePath = path.join(ICONS_PATH, category, style)

            // Components
            styleIcons.forEach(icon => {
                files.push(Generators.component(icon))
                // Add aliases
                const aliases = getAliasesForIcon(icon.pascalName)
                aliases.forEach(alias => {
                    files.push(Generators.aliasComponent(icon, alias))
                })
            })

            // Style Indexes
            files.push(Generators.styleIndex(style, styleIcons, stylePath))
            files.push(Generators.styleGlobalIndex(style, styleIcons, stylePath))
        }

        // Category Indexes
        const styles = Object.keys(byStyle)
        const categoryPath = path.join(ICONS_PATH, category)
        files.push(Generators.categoryIndex(category, styles, categoryPath))
        files.push(Generators.categoryGlobalIndex(category, styles, categoryPath))
    }

    // 2. Root Indexes
    const categories = Object.keys(byCategory)
    files.push(Generators.rootIndex(categories))
    files.push(Generators.rootGlobalIndex(categories))

    // 3. Weight/Style Indexes
    files.push(...Generators.weightIndexes(icons))
    files.push(Generators.stylesIndex())

    // 4. Main Entry
    files.push(Generators.mainEntry())

    return files
}

function writeFiles(files: FileDefinition[]) {
    files.forEach(file => {
        fs.mkdirSync(path.dirname(file.path), { recursive: true })
        fs.writeFileSync(file.path, file.content, { flag: 'w' })
    })
    console.log(pc.green(`Successfully generated ${files.length} files.`))
}

// --- Main ---

const main = async () => {
    try {
        clean()
        const svgMap = readSvgsFromDisk()
        if (!verifyIcons(svgMap)) {
            process.exit(1)
        }
        const icons = getIcons(svgMap)
        const files = generate(icons)
        writeFiles(files)
    } catch (err) {
        console.error(pc.red('Build failed'))
        console.error(err)
        process.exit(1)
    }
}

await main()

// packages/angular/scripts/generate-assets.ts
#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import pc from 'picocolors'

/**
 * Dictionary of icon name corrections (typos from Figma source)
 */
// cspell:disable - These are intentional typos that map to corrections
const ICON_RENAMES: Record<string, string> = {
    Magnifer: 'Magnifier',
    Infinity: 'Infinite',
    Condicioner: 'Conditioner',
    Siderbar: 'Sidebar',
    Plaaylist: 'Playlist',
    Pallete: 'Palette',
    Tuneing: 'Tuning',
    // Only replace 'Horizonta' if it's NOT followed by an 'l'
    'Horizonta(?![l])': 'Horizontal',
    Minimlistic: 'Minimalistic',
    Spedometer: 'Speedometer',
    Happly: 'Happy',
    Clound: 'Cloud',
    Recive: 'Receive',
}
// cspell:enable
import type { SvgMap } from './utils'
import {
    ICONS_PATH,
    INDEX_PATH,
    nodesToTemplate,
    readSvgsFromDisk,
    toPascalCase,
    verifyIcons,
    WEIGHTS,
} from './utils'

// Create a reverse mapping for aliases (Correction -> [Typos])
const ICON_ALIASES: Record<string, string[]> = {}
for (const [typo, correction] of Object.entries(ICON_RENAMES)) {
    if (!ICON_ALIASES[correction]) {
        ICON_ALIASES[correction] = []
    }
    ICON_ALIASES[correction].push(typo)
}

// --- Types ---

interface Icon {
    category: string
    style: string
    name: string // kebab-case (e.g. arrow-left)
    pascalName: string // PascalCase (e.g. ArrowLeft)
    globalName: string // Disambiguated Name (e.g. ArrowLeftBold)
    preview: string // base64 preview
    template: string // Angular template string
}

interface FileDefinition {
    path: string
    content: string
}

// --- Helpers ---

/**
 * Flattens the nested SvgMap into a list of Icon objects.
 */
function getIcons(map: SvgMap): Icon[] {
    const icons: Icon[] = []
    for (const [category, styles] of Object.entries(map)) {
        for (const [style, names] of Object.entries(styles)) {
            for (const [name, data] of Object.entries(names)) {
                // Parse the node string back to IconNode array to generate template
                const nodeArray = eval(data.node) // Safe since we generated this ourselves
                const template = nodesToTemplate(nodeArray)

                icons.push({
                    category,
                    style,
                    name,
                    pascalName: toPascalCase(name),
                    globalName: toPascalCase(`${name}-${style}`),
                    preview: data.preview,
                    template,
                })
            }
        }
    }
    return icons
}

/**
 * Utility to group icons by a specific key.
 */
function groupBy<T>(array: T[], keySelector: (item: T) => string): Record<string, T[]> {
    return array.reduce(
        (acc, item) => {
            const key = keySelector(item)
            if (!acc[key]) acc[key] = []
            acc[key].push(item)
            return acc
        },
        {} as Record<string, T[]>
    )
}

/**
 * Returns a list of aliases (typos) for a given icon name.
 */
function getAliasesForIcon(name: string): string[] {
    const aliases = new Set<string>()
    if (ICON_ALIASES[name]) {
        ICON_ALIASES[name].forEach(a => aliases.add(a))
    }
    Object.entries(ICON_ALIASES).forEach(([correct, typos]) => {
        if (name.includes(correct) && name !== correct) {
            typos.forEach(typo => {
                if (/[^a-z0-9]/i.test(typo)) return
                aliases.add(name.replace(correct, typo))
            })
        }
    })
    return Array.from(aliases).filter(a => a !== name)
}

// --- Generators ---

const Generators = {
    component: (icon: Icon): FileDefinition => {
        const content = `/* GENERATED FILE */
import {
    ChangeDetectionStrategy,
    Component,
    ViewEncapsulation,
} from '@angular/core';
import { IconBase, SOLAR_ICON_HOST_DIRECTIVES } from '../../../lib/icon-base';

/**
 * ![img](data:image/svg+xml;base64,${icon.preview})
 *
 * @usage
 * \`<svg solar${icon.globalName}></svg>\`
 *
 * @component ${icon.globalName}
 * @style ${icon.style}
 * @category ${icon.category}
 */
@Component({
    selector: 'svg[solar${icon.globalName}]',
    template: \`${icon.template}\`,
    standalone: true,
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.OnPush,
    host: {
        xmlns: 'http://www.w3.org/2000/svg',
        viewBox: '0 0 24 24',
        fill: 'none',
        class: 'solar-icon',
        '[attr.width]': 'size()',
        '[attr.height]': 'size()',
        '[style.color]': 'color()',
        '[attr.transform]': 'mirrored() ? "scale(-1, 1)" : null',
        '[attr.aria-hidden]': 'alt() ? null : "true"',
    },
    hostDirectives: SOLAR_ICON_HOST_DIRECTIVES,
})
export class ${icon.globalName} extends IconBase {}
`
        return {
            path: path.join(ICONS_PATH, icon.category, icon.style, `${icon.globalName}.ts`),
            content,
        }
    },

    aliasComponent: (icon: Icon, alias: string): FileDefinition => {
        const aliasGlobal = `${alias}${icon.style}`
        const content = `/* GENERATED FILE */
import { ${icon.globalName} } from './${icon.globalName}';

/**
 * @deprecated Use ${icon.globalName} instead
 */
export const ${aliasGlobal} = ${icon.globalName};
`
        return {
            path: path.join(ICONS_PATH, icon.category, icon.style, `${aliasGlobal}.ts`),
            content,
        }
    },

    /**
     * Generates the index.ts for a category.
     */
    categoryIndex: (category: string, icons: Icon[], folderPath: string): FileDefinition => {
        let exports = icons
            .map(
                icon =>
                    `export { ${icon.globalName} } from './${icon.style}/${icon.globalName}';`
            )
            .sort()
            .join('\n')

        icons.forEach(icon => {
            const aliases = getAliasesForIcon(icon.pascalName)
            aliases.forEach(alias => {
                exports += `\nexport { ${alias}${icon.style} } from './${icon.style}/${alias}${icon.style}';`
            })
        })

        return {
            path: path.join(folderPath, 'index.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the styled.ts for a category.
     */
    categoryGlobalIndex: (
        category: string,
        styles: string[],
        folderPath: string
    ): FileDefinition => {
        const exports = styles
            .map(style => `export * from './${style}/styled';`)
            .sort()
            .join('\n')

        return {
            path: path.join(folderPath, 'styled.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the root index.ts.
     */
    rootIndex: (categories: string[]): FileDefinition => {
        const exports = categories
            .map(category => `export * from './${category}';`)
            .sort()
            .join('\n')

        return {
            path: path.join(ICONS_PATH, 'index.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the main entry point (public-api.ts).
     * Note: no `import * as solar` re-export — that would create a circular
     * dependency since the barrel already re-exports everything flat.
     */
    mainEntry: (): FileDefinition => {
        const content = `/* GENERATED FILE */
export * from './lib';
export * from './icons';
`
        return {
            path: INDEX_PATH,
            content,
        }
    },
}

// --- Stages ---

function clean() {
    const pathsToClean = [ICONS_PATH, INDEX_PATH]
    pathsToClean.forEach(p => {
        if (fs.existsSync(p)) {
            fs.rmSync(p, { recursive: true, force: true })
            console.log(pc.blue(`Removed ${p}`))
        }
    })
}

function generate(icons: Icon[]) {
    const files: FileDefinition[] = []

    const byCategory = groupBy(icons, i => i.category)

    for (const [category, catIcons] of Object.entries(byCategory)) {
        const byStyle = groupBy(catIcons, i => i.style)

        for (const [style, styleIcons] of Object.entries(byStyle)) {
            const stylePath = path.join(ICONS_PATH, category, style)

            styleIcons.forEach(icon => {
                files.push(Generators.component(icon))
                const aliases = getAliasesForIcon(icon.pascalName)
                aliases.forEach(alias => {
                    files.push(Generators.aliasComponent(icon, alias))
                })
            })
            // We no longer generate style indexes
        }

        const categoryPath = path.join(ICONS_PATH, category)
        files.push(Generators.categoryIndex(category, catIcons, categoryPath))
    }

    const categories = Object.keys(byCategory)
    files.push(Generators.rootIndex(categories))

    files.push(Generators.mainEntry())

    return files
}

function writeFiles(files: FileDefinition[]) {
    files.forEach(file => {
        fs.mkdirSync(path.dirname(file.path), { recursive: true })
        fs.writeFileSync(file.path, file.content, { flag: 'w' })
    })
    console.log(pc.green(`Successfully generated ${files.length} files.`))
}

// --- Main ---

void (async () => {
    try {
        clean()
        const svgMap = readSvgsFromDisk()
        if (!verifyIcons(svgMap)) {
            process.exit(1)
        }
        const icons = getIcons(svgMap)
        const files = generate(icons)
        writeFiles(files)
    } catch (err) {
        console.error(pc.red('Build failed'))
        console.error(err)
        process.exit(1)
    }
})()
