// packages/react/scripts/generate-assets.ts
#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import pc from 'picocolors'

import { ICON_RENAMES } from '../../core/src/utils'
import type { SvgMap } from './utils'
import {
    CSR_PATH,
    DEFS_PATH,
    INDEX_PATH,
    readSvgsFromDisk,
    SSR_PATH,
    toPascalCase,
    verifyIcons,
} from './utils'

// Create a reverse mapping for aliases (Correction -> [Typos])
const ICON_ALIASES: Record<string, string[]> = {}
for (const [typo, correction] of Object.entries(ICON_RENAMES)) {
    if (!ICON_ALIASES[correction]) {
        ICON_ALIASES[correction] = []
    }
    ICON_ALIASES[correction].push(typo)
}

/**
 * Returns a list of aliases (typos) for a given icon name, including partial matches.
 */
function getAliasesForIcon(name: string): string[] {
    const aliases = new Set<string>()
    // Exact matches
    if (ICON_ALIASES[name]) {
        ICON_ALIASES[name].forEach(a => aliases.add(a))
    }
    // Partial matches
    Object.entries(ICON_ALIASES).forEach(([correct, typos]) => {
        if (name.includes(correct) && name !== correct) {
            typos.forEach(typo => {
                if (/[^a-z0-9]/i.test(typo)) return
                aliases.add(name.replace(correct, typo))
            })
        }
    })
    return Array.from(aliases).filter(a => a !== name)
}

/**
 * Clean generated directories and files to ensure a clean build.
 *
 * The following directories and files are removed:
 * - src/csr
 * - src/ssr
 * - src/defs
 * - src/index.ts
 */
function cleanGeneratedDirectoriesAndFiles() {
    const pathsToClean = [CSR_PATH, SSR_PATH, DEFS_PATH, INDEX_PATH]

    pathsToClean.forEach(pathToClean => {
        if (fs.existsSync(pathToClean)) {
            fs.rmSync(pathToClean, { recursive: true, force: true })
            console.log(pc.blue(`Removed ${pathToClean}`))
        }
    })
}

/**
 * Generates React components for icons based on the given grouping and type.
 * @param groupedIcons - An object representing icons grouped by category.
 * Each category contains icons with different styles.
 * @param type - The type of component to generate, either 'csr' (Client Side Rendering)
 * or 'ssr' (Server Side Rendering), which determines the base component and path used.
 *
 * The function creates TypeScript files for each icon, including a forwardRef
 * component for rendering the icon with different styles. It also generates index
 * files for each category and a global index file.
 */
function generateReactComponents(
    groupedIcons: ReturnType<typeof groupIconsByName>,
    type: 'csr' | 'ssr'
) {
    const BASE_PATH = type === 'csr' ? CSR_PATH : SSR_PATH
    const importBase = type === 'csr' ? 'IconBase' : 'SSRBase'
    const useClientDirective = type === 'csr' ? `'use client'\n\n` : ''

    for (const category in groupedIcons) {
        const categoryPath = path.join(BASE_PATH, category)
        fs.mkdirSync(categoryPath, { recursive: true })

        const iconsInCategory = groupedIcons[category]
        let categoryIndexContent = ''

        for (const iconName in iconsInCategory) {
            const name = toPascalCase(iconName)

            const doc = `/**
${Object.entries(iconsInCategory[iconName]!)
    .map(([style, { preview }]) => ` * ### ![img](data:image/svg+xml;base64,${preview}) ${style}`)
    .join('\n')}
 */`

            const componentContent = `${useClientDirective}/* GENERATED FILE */
import React, { forwardRef } from "react"
import type { IconProps, Icon } from "../../lib/types"
import ${importBase} from "../../lib/${importBase}"
import weights from "../../defs/${category}/${name}"

${doc}
const ${name}: Icon = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
    <${importBase} ref={ref} {...props} weights={weights} />
))

${name}.displayName = "${name}"
export default ${name}
`

            fs.writeFileSync(path.join(categoryPath, `${name}.tsx`), componentContent, {
                flag: 'w',
            })

            categoryIndexContent += `export { default as ${name} } from './${name}'\n`

            // Add aliases if they exist
            const aliases = getAliasesForIcon(name)
            if (aliases.length > 0) {
                aliases.forEach(alias => {
                    const aliasContent = `import target from './${name}'
/**
 * @deprecated Use ${name} instead
 */
const ${alias} = target
export default ${alias}
`
                    fs.writeFileSync(path.join(categoryPath, `${alias}.ts`), aliasContent, {
                        flag: 'w',
                    })

                    categoryIndexContent += `export { default as ${alias} } from './${alias}'\n`
                })
            }
        }

        fs.writeFileSync(path.join(categoryPath, 'index.ts'), categoryIndexContent, { flag: 'w' })
    }

    // Generate global index
    let globalIndexContent = Object.keys(groupedIcons)
        .map(category => {
            return `export * from './${category}'`
        })
        .join('\n')

    globalIndexContent += '\nexport * as category from "./category"'

    fs.writeFileSync(path.join(BASE_PATH, 'index.ts'), globalIndexContent, { flag: 'w' })

    // Generate category index
    const globalCategoryIndexContent = Object.keys(groupedIcons)
        .map(category => {
            const categoryName = toPascalCase(category)
            return `export * as ${categoryName} from './${category}'`
        })
        .join('\n')

    fs.writeFileSync(path.join(BASE_PATH, 'category.ts'), globalCategoryIndexContent, { flag: 'w' })
}

/**
 * Generates TypeScript definition files for icons based on the given grouping.
 *
 * This function iterates over grouped icons by category and creates TypeScript
 * files for each icon, storing their style-specific JSX representations in a Map.
 * It also generates index files for each category and a global index file.
 * @param groupedIcons - An object with icons grouped by category and name,
 * each containing style-specific properties, including JSX representation.
 */
function generateIconDefinitions(groupedIcons: ReturnType<typeof groupIconsByName>) {
    for (const category in groupedIcons) {
        const categoryDefsPath = path.join(DEFS_PATH, category)
        fs.mkdirSync(categoryDefsPath, { recursive: true })

        const iconsInCategory = groupedIcons[category]
        let categoryIndexContent = ''

        for (const iconName in iconsInCategory) {
            const iconStyles = iconsInCategory[iconName]
            const name = toPascalCase(iconName)

            const defContent = `/* GENERATED FILE */
import React, { ReactElement } from "react"
import type { IconWeight } from '../../lib'

export default new Map<IconWeight, ReactElement>([
${Object.entries(iconStyles!)
    .map(([style, { jsx }]) => `  ["${style}", <>${jsx.trim()}</>]`)
    .join(',\n')}
]);
`

            fs.writeFileSync(path.join(categoryDefsPath, `${name}.tsx`), defContent, { flag: 'w' })

            categoryIndexContent += `export { default as ${name} } from './${name}';\n`
        }

        fs.writeFileSync(path.join(categoryDefsPath, 'index.ts'), categoryIndexContent, {
            flag: 'w',
        })
    }

    // Generate global index
    const globalIndexContent = Object.keys(groupedIcons)
        .map(category => {
            return `export * from './${category}';`
        })
        .join('\n')

    fs.writeFileSync(path.join(DEFS_PATH, 'index.ts'), globalIndexContent, { flag: 'w' })
}

/**
 * Groups icons by their name within each category and style.
 *
 * This function takes an SvgMap of icons organized by category and style,
 * and reorganizes it into a nested structure where icons are grouped by their
 * names within each category. Each icon retains its style-specific properties,
 * including a preview and jsx representation.
 * @param icons - The SvgMap containing icons organized by category and style.
 * @returns A nested object where icons are grouped by name within each category,
 *          with style-specific properties for each icon.
 */
function groupIconsByName(icons: SvgMap) {
    const groupedIcons: Record<
        string, // Category
        Record<
            string, // Name
            Record<
                string, // Style
                { preview: string; jsx: string }
            >
        >
    > = {}

    for (const category in icons) {
        groupedIcons[category] = {}

        const styles = icons[category]
        for (const style in styles) {
            const iconsInStyle = styles[style]
            for (const iconName in iconsInStyle) {
                if (!groupedIcons[category][iconName]) {
                    groupedIcons[category][iconName] = {}
                }
                groupedIcons[category][iconName][style] = iconsInStyle[iconName]!
            }
        }
    }

    return groupedIcons
}

/**
 * Generates React components and TypeScript definitions for each icon.
 *
 * This function groups icons by name within each category and generates
 * React components and TypeScript definitions for each icon. It also generates
 * index files for each category and a global index file.
 * @param icons - The SvgMap containing icons organized by category and style.
 */
function generateComponents(icons: SvgMap) {
    // Create directories if they don't exist
    fs.mkdirSync(CSR_PATH, { recursive: true })
    fs.mkdirSync(SSR_PATH, { recursive: true })
    fs.mkdirSync(DEFS_PATH, { recursive: true })

    // Group icons by name
    const groupedIcons = groupIconsByName(icons)

    // Generate icon definitions
    generateIconDefinitions(groupedIcons)

    // Generate React components
    generateReactComponents(groupedIcons, 'csr')
    generateReactComponents(groupedIcons, 'ssr')

    console.log('Generated assets successfully')
}

/**
 * Generates the main export index file for the library.
 *
 * This function creates a TypeScript index file that exports essential types,
 * contexts, and components from the library's source directories. It includes:
 * - Type exports for IconProps and IconWeight.
 * - Named exports for IconContext and IconBase.
 * - Namespace export for server-side rendering components (SSR).
 * - All exports from client-side rendering components (CSR).
 *
 * The generated file is written to the path specified by INDEX_PATH.
 * Logs the success or failure of the export operation.
 */
function generateMainExports() {
    const mainIndexContent = `\
/* GENERATED FILE */
export type { IconProps, IconWeight } from "./lib"
export { SolarProvider, useSolar, IconBase } from "./lib"
export * as SSR from "./ssr"
export * from "./csr"
import * as solar from "./csr/category"
export { solar }
export default solar
`

    try {
        // Write the main export index
        fs.writeFileSync(INDEX_PATH, mainIndexContent, { flag: 'w' })
        console.log(pc.green('Main index export success'))
    } catch (err) {
        console.error(pc.red('Main index export failed'))
        console.group()
        console.error(err)
        console.groupEnd()
    }
}

/**
 * Main function to generate the entire library.
 *
 * This function does the following in order:
 * 1. Deletes old files and directories before starting the build.
 * 2. Reads icon data from disk and verifies integrity.
 * 3. Generates components for each icon.
 * 4. Generates main export index.
 *
 * Exits the process if icon integrity verification fails.
 */
const main = async () => {
    // Delete old files and directories before starting the build
    cleanGeneratedDirectoriesAndFiles()

    // Read icon data from disk and verify integrity
    const icons = readSvgsFromDisk()
    if (!verifyIcons(icons)) {
        process.exit(1)
    }

    generateComponents(icons) // Generate components for each icon
    generateMainExports() // Generate main export index
}

await main()

// packages/angular/scripts/generate-assets.ts
#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import pc from 'picocolors'

/**
 * Dictionary of icon name corrections (typos from Figma source)
 */
// cspell:disable - These are intentional typos that map to corrections
const ICON_RENAMES: Record<string, string> = {
    Magnifer: 'Magnifier',
    Infinity: 'Infinite',
    Condicioner: 'Conditioner',
    Siderbar: 'Sidebar',
    Plaaylist: 'Playlist',
    Pallete: 'Palette',
    Tuneing: 'Tuning',
    // Only replace 'Horizonta' if it's NOT followed by an 'l'
    'Horizonta(?![l])': 'Horizontal',
    Minimlistic: 'Minimalistic',
    Spedometer: 'Speedometer',
    Happly: 'Happy',
    Clound: 'Cloud',
    Recive: 'Receive',
}
// cspell:enable
import type { SvgMap } from './utils'
import {
    ICONS_PATH,
    INDEX_PATH,
    nodesToTemplate,
    readSvgsFromDisk,
    toPascalCase,
    verifyIcons,
    WEIGHTS,
} from './utils'

// Create a reverse mapping for aliases (Correction -> [Typos])
const ICON_ALIASES: Record<string, string[]> = {}
for (const [typo, correction] of Object.entries(ICON_RENAMES)) {
    if (!ICON_ALIASES[correction]) {
        ICON_ALIASES[correction] = []
    }
    ICON_ALIASES[correction].push(typo)
}

// --- Types ---

interface Icon {
    category: string
    style: string
    name: string // kebab-case (e.g. arrow-left)
    pascalName: string // PascalCase (e.g. ArrowLeft)
    globalName: string // Disambiguated Name (e.g. ArrowLeftBold)
    preview: string // base64 preview
    template: string // Angular template string
}

interface FileDefinition {
    path: string
    content: string
}

// --- Helpers ---

/**
 * Flattens the nested SvgMap into a list of Icon objects.
 */
function getIcons(map: SvgMap): Icon[] {
    const icons: Icon[] = []
    for (const [category, styles] of Object.entries(map)) {
        for (const [style, names] of Object.entries(styles)) {
            for (const [name, data] of Object.entries(names)) {
                // Parse the node string back to IconNode array to generate template
                const nodeArray = eval(data.node) // Safe since we generated this ourselves
                const template = nodesToTemplate(nodeArray)

                icons.push({
                    category,
                    style,
                    name,
                    pascalName: toPascalCase(name),
                    globalName: toPascalCase(`${name}-${style}`),
                    preview: data.preview,
                    template,
                })
            }
        }
    }
    return icons
}

/**
 * Utility to group icons by a specific key.
 */
function groupBy<T>(array: T[], keySelector: (item: T) => string): Record<string, T[]> {
    return array.reduce(
        (acc, item) => {
            const key = keySelector(item)
            if (!acc[key]) acc[key] = []
            acc[key].push(item)
            return acc
        },
        {} as Record<string, T[]>
    )
}

/**
 * Returns a list of aliases (typos) for a given icon name.
 */
function getAliasesForIcon(name: string): string[] {
    const aliases = new Set<string>()
    if (ICON_ALIASES[name]) {
        ICON_ALIASES[name].forEach(a => aliases.add(a))
    }
    Object.entries(ICON_ALIASES).forEach(([correct, typos]) => {
        if (name.includes(correct) && name !== correct) {
            typos.forEach(typo => {
                if (/[^a-z0-9]/i.test(typo)) return
                aliases.add(name.replace(correct, typo))
            })
        }
    })
    return Array.from(aliases).filter(a => a !== name)
}

// --- Generators ---

const Generators = {
    component: (icon: Icon): FileDefinition => {
        const content = `/* GENERATED FILE */
import {
    ChangeDetectionStrategy,
    Component,
    ViewEncapsulation,
} from '@angular/core';
import { IconBase, SOLAR_ICON_HOST_DIRECTIVES } from '../../../lib/icon-base';

/**
 * ![img](data:image/svg+xml;base64,${icon.preview})
 *
 * @usage
 * \`<svg solar${icon.globalName}></svg>\`
 *
 * @component ${icon.globalName}
 * @style ${icon.style}
 * @category ${icon.category}
 */
@Component({
    selector: 'svg[solar${icon.globalName}]',
    template: \`${icon.template}\`,
    standalone: true,
    encapsulation: ViewEncapsulation.None,
    changeDetection: ChangeDetectionStrategy.OnPush,
    host: {
        xmlns: 'http://www.w3.org/2000/svg',
        viewBox: '0 0 24 24',
        fill: 'none',
        class: 'solar-icon',
        '[attr.width]': 'size()',
        '[attr.height]': 'size()',
        '[style.color]': 'color()',
        '[attr.transform]': 'mirrored() ? "scale(-1, 1)" : null',
        '[attr.aria-hidden]': 'alt() ? null : "true"',
    },
    hostDirectives: SOLAR_ICON_HOST_DIRECTIVES,
})
export class ${icon.globalName} extends IconBase {}
`
        return {
            path: path.join(ICONS_PATH, icon.category, icon.style, `${icon.globalName}.ts`),
            content,
        }
    },

    aliasComponent: (icon: Icon, alias: string): FileDefinition => {
        const aliasGlobal = `${alias}${icon.style}`
        const content = `/* GENERATED FILE */
import { ${icon.globalName} } from './${icon.globalName}';

/**
 * @deprecated Use ${icon.globalName} instead
 */
export const ${aliasGlobal} = ${icon.globalName};
`
        return {
            path: path.join(ICONS_PATH, icon.category, icon.style, `${aliasGlobal}.ts`),
            content,
        }
    },

    /**
     * Generates the index.ts for a category.
     */
    categoryIndex: (category: string, icons: Icon[], folderPath: string): FileDefinition => {
        let exports = icons
            .map(
                icon =>
                    `export { ${icon.globalName} } from './${icon.style}/${icon.globalName}';`
            )
            .sort()
            .join('\n')

        icons.forEach(icon => {
            const aliases = getAliasesForIcon(icon.pascalName)
            aliases.forEach(alias => {
                exports += `\nexport { ${alias}${icon.style} } from './${icon.style}/${alias}${icon.style}';`
            })
        })

        return {
            path: path.join(folderPath, 'index.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the styled.ts for a category.
     */
    categoryGlobalIndex: (
        category: string,
        styles: string[],
        folderPath: string
    ): FileDefinition => {
        const exports = styles
            .map(style => `export * from './${style}/styled';`)
            .sort()
            .join('\n')

        return {
            path: path.join(folderPath, 'styled.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the root index.ts.
     */
    rootIndex: (categories: string[]): FileDefinition => {
        const exports = categories
            .map(category => `export * from './${category}';`)
            .sort()
            .join('\n')

        return {
            path: path.join(ICONS_PATH, 'index.ts'),
            content: `${exports}\n`,
        }
    },

    /**
     * Generates the main entry point (public-api.ts).
     * Note: no `import * as solar` re-export — that would create a circular
     * dependency since the barrel already re-exports everything flat.
     */
    mainEntry: (): FileDefinition => {
        const content = `/* GENERATED FILE */
export * from './lib';
export * from './icons';
`
        return {
            path: INDEX_PATH,
            content,
        }
    },
}

// --- Stages ---

function clean() {
    const pathsToClean = [ICONS_PATH, INDEX_PATH]
    pathsToClean.forEach(p => {
        if (fs.existsSync(p)) {
            fs.rmSync(p, { recursive: true, force: true })
            console.log(pc.blue(`Removed ${p}`))
        }
    })
}

function generate(icons: Icon[]) {
    const files: FileDefinition[] = []

    const byCategory = groupBy(icons, i => i.category)

    for (const [category, catIcons] of Object.entries(byCategory)) {
        const byStyle = groupBy(catIcons, i => i.style)

        for (const [style, styleIcons] of Object.entries(byStyle)) {
            const stylePath = path.join(ICONS_PATH, category, style)

            styleIcons.forEach(icon => {
                files.push(Generators.component(icon))
                const aliases = getAliasesForIcon(icon.pascalName)
                aliases.forEach(alias => {
                    files.push(Generators.aliasComponent(icon, alias))
                })
            })
            // We no longer generate style indexes
        }

        const categoryPath = path.join(ICONS_PATH, category)
        files.push(Generators.categoryIndex(category, catIcons, categoryPath))
    }

    const categories = Object.keys(byCategory)
    files.push(Generators.rootIndex(categories))

    files.push(Generators.mainEntry())

    return files
}

function writeFiles(files: FileDefinition[]) {
    files.forEach(file => {
        fs.mkdirSync(path.dirname(file.path), { recursive: true })
        fs.writeFileSync(file.path, file.content, { flag: 'w' })
    })
    console.log(pc.green(`Successfully generated ${files.length} files.`))
}

// --- Main ---

void (async () => {
    try {
        clean()
        const svgMap = readSvgsFromDisk()
        if (!verifyIcons(svgMap)) {
            process.exit(1)
        }
        const icons = getIcons(svgMap)
        const files = generate(icons)
        writeFiles(files)
    } catch (err) {
        console.error(pc.red('Build failed'))
        console.error(err)
        process.exit(1)
    }
})()
