// apps/vue-app/src/components/ProviderDemo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { SolarProvider } from '@solar-icons/vue'
import ProviderDemoInner from './ProviderDemoInner.vue'

const providerColor = ref('#f59e0b')
const providerSize = ref(36)
const providerStroke = ref(1.5)
</script>

<template>
    <div>
        <div class="flex items-center gap-4 mb-4">
            <div class="space-y-1">
                <span class="text-xs">Color</span>
                <input type="color" v-model="providerColor" class="w-8 h-8 rounded border-0" />
            </div>
            <div class="space-y-1">
                <span class="text-xs">Size ({{ providerSize }}px)</span>
                <input type="range" min="16" max="64" v-model.number="providerSize" class="w-24" />
            </div>
            <div class="space-y-1">
                <span class="text-xs">Stroke ({{ providerStroke }})</span>
                <input type="range" min="0.5" max="3" step="0.1" v-model.number="providerStroke" class="w-24" />
            </div>
            <div class="space-y-1">
                <span class="text-xs">Mirror</span>
                <label class="flex items-center gap-1 cursor-pointer text-xs">
                </label>
            </div>
        </div>
            <div class="bg-muted/30 rounded-lg p-4">
                <ProviderDemoInner />
            </div>
        </SolarProvider>
    </div>
</template>

// apps/svelte-app/src/lib/ProviderDemo.svelte
<script lang="ts">
    import SolarProvider from '@solar-icons/svelte/lib/SolarProvider.svelte';
    import ProviderDemoInner from './ProviderDemoInner.svelte';

    let providerColor = $state('#f59e0b');
    let providerSize = $state(36);
    let providerStroke = $state(1.5);
</script>

<div>
    <div class="flex items-center gap-4 mb-4">
        <div class="space-y-1">
            <span class="text-xs text-slate-400">Color</span>
            <input
                type="color"
                bind:value={providerColor}
                class="w-10 h-10 rounded cursor-pointer border-0"
            />
        </div>
        <div class="space-y-1">
            <span class="text-xs text-slate-400">Size ({providerSize}px)</span>
            <input
                type="range"
                min="16"
                max="64"
                bind:value={providerSize}
                class="w-32 accent-amber-500"
            />
        </div>
        <div class="space-y-1">
            <span class="text-xs text-slate-400">Stroke ({providerStroke})</span>
            <input
                type="range"
                min="0.5"
                max="3"
                step="0.1"
                bind:value={providerStroke}
                class="w-32 accent-amber-500"
            />
        </div>
        <div class="space-y-1">
            <span class="text-xs text-slate-400">Mirror</span>
            <label class="flex items-center gap-2 cursor-pointer"> </label>
        </div>
    </div>

    <SolarProvider color={providerColor} size={providerSize} strokeWidth={providerStroke}>
        <div class="bg-slate-900 rounded-lg p-4">
            <ProviderDemoInner />
        </div>
    </SolarProvider>
</div>
