// packages/solid/src/lib/types.ts
import type { JSX } from 'solid-js';

export enum IconStyle {
    BROKEN = 'Broken',
    LINE_DUOTONE = 'LineDuotone',
    LINEAR = 'Linear',
    OUTLINE = 'Outline',
    BOLD = 'Bold',
    BOLD_DUOTONE = 'BoldDuotone',
}

export interface IconBaseProps {
    alt?: string;
    color?: string;
    size?: string | number;
    strokeWidth?: string | number;
    secondaryColor?: string;
    secondaryOpacity?: number;
    iconName?: string;
}

export type SvgSVGAttributes = JSX.SvgSVGAttributes<SVGSVGElement>;

export interface IconProps extends IconBaseProps {
    color?: string;
    children?: JSX.Element;
}

export type Icon = (props: IconProps) => JSX.Element;

// packages/react-native/src/lib/types.ts
import type { SvgProps } from 'react-native-svg'

export enum IconStyle {
    BOLD = 'Bold',
    BOLD_DUOTONE = 'BoldDuotone',
    BROKEN = 'Broken',
    LINE_DUOTONE = 'LineDuotone',
    LINEAR = 'Linear',
    OUTLINE = 'Outline',
}

export interface IconBaseProps {
    alt?: string
    color?: string
    size?: number
    strokeWidth?: number | string
    secondaryColor?: string
    secondaryOpacity?: number
    children?: any
}

export interface IconProps extends Omit<SvgProps, 'width' | 'height'> {
    size?: number
    color?: string
    strokeWidth?: number | string
    secondaryColor?: string
    secondaryOpacity?: number
}

export type Icon = React.ForwardRefExoticComponent<IconProps & React.RefAttributes<any>>
