// apps/vue-app/src/components/ui/slider/Slider.vue
<script setup lang="ts">
import { reactiveOmit } from '@vueuse/core'
import type { SliderRootEmits, SliderRootProps } from 'reka-ui'
import { SliderRange, SliderRoot, SliderThumb, SliderTrack, useForwardPropsEmits } from 'reka-ui'
import type { HTMLAttributes } from 'vue'

import { cn } from '@/lib/utils'

const props = defineProps<SliderRootProps & { class?: HTMLAttributes['class'] }>()
const emits = defineEmits<SliderRootEmits>()

const delegatedProps = reactiveOmit(props, 'class')

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
    <SliderRoot
        v-slot="{ modelValue }"
        data-slot="slider"
        :class="
            cn(
                'relative flex w-full touch-none items-center select-none data-[disabled]:opacity-50 data-[orientation=vertical]:h-full data-[orientation=vertical]:min-h-44 data-[orientation=vertical]:w-auto data-[orientation=vertical]:flex-col',
                props.class
            )
        "
        v-bind="forwarded">
        <SliderTrack
            data-slot="slider-track"
            class="bg-muted relative grow overflow-hidden rounded-full data-[orientation=horizontal]:h-1.5 data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-1.5">
            <SliderRange
                data-slot="slider-range"
                class="bg-primary absolute data-[orientation=horizontal]:h-full data-[orientation=vertical]:w-full" />
        </SliderTrack>

        <SliderThumb
            v-for="(_, key) in modelValue"
            :key="key"
            data-slot="slider-thumb"
            class="border-primary bg-background ring-ring/50 block size-4 shrink-0 rounded-full border shadow-sm transition-[color,box-shadow] hover:ring-4 focus-visible:ring-4 focus-visible:outline-hidden disabled:pointer-events-none disabled:opacity-50" />
    </SliderRoot>
</template>

// apps/docs/components/ui/slider.tsx
'use client'

import * as SliderPrimitive from '@radix-ui/react-slider'
import * as React from 'react'

import { cn } from '@/lib/utils'

const Slider = React.forwardRef<
    React.ElementRef<typeof SliderPrimitive.Root>,
    React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root>
>(({ className, ...props }, ref) => (
    <SliderPrimitive.Root
        ref={ref}
        data-slot="slider"
        className={cn('relative flex w-full touch-none items-center select-none', className)}
        {...props}>
        <SliderPrimitive.Track
            data-slot="slider-track"
            className={`relative h-0.5 w-full grow overflow-hidden rounded-full bg-foreground/20`}>
            <SliderPrimitive.Range
                data-slot="slider-range"
                className="absolute h-full bg-foreground"
            />
        </SliderPrimitive.Track>
        <SliderPrimitive.Thumb
            data-slot="slider-thumb"
            className={`
              block size-4 rounded-full border border-foreground/50 bg-background shadow-sm
              transition-all
              hover:size-5 hover:shadow-md
              focus-visible:ring-1 focus-visible:ring-ring focus-visible:outline-hidden
              disabled:pointer-events-none disabled:opacity-50
            `}
        />
    </SliderPrimitive.Root>
))
Slider.displayName = SliderPrimitive.Root.displayName

export { Slider }
