// packages/angular/src/lib/solar-provider.ts
import {
    Component,
    effect,
    inject,
    Injectable,
    input,
    signal,
    viewChild,
    type ElementRef,
} from '@angular/core'

@Injectable()
export class SolarService {
    private wrapperEl: HTMLDivElement | null = null

    readonly color = signal<string | undefined>(undefined)
    readonly size = signal<string | number | undefined>(undefined)
    readonly strokeWidth = signal<number | undefined>(undefined)
    readonly duotoneColor = signal<string | undefined>(undefined)
    readonly duotoneOpacity = signal<number | undefined>(undefined)
    readonly mirrored = signal<boolean | undefined>(undefined)

    registerWrapper(el: HTMLDivElement) {
        this.wrapperEl = el
    }

    setColor(val: string) {
        this.color.set(val)
        this.wrapperEl?.style.setProperty('--solar-icon-color', val)
    }

    setSize(val: string | number) {
        this.size.set(val)
        this.wrapperEl?.style.setProperty(
            '--solar-icon-size',
            typeof val === 'number' ? `${val}px` : val
        )
    }

    setStrokeWidth(val: number) {
        this.strokeWidth.set(val)
        this.wrapperEl?.style.setProperty('--solar-stroke-width', String(val))
    }

    setDuotoneColor(val: string) {
        this.duotoneColor.set(val)
        this.wrapperEl?.style.setProperty('--solar-duotone-color', val)
    }

    setDuotoneOpacity(val: number) {
        this.duotoneOpacity.set(val)
        this.wrapperEl?.style.setProperty('--solar-duotone-opacity', String(val))
    }

    setMirrored(val: boolean) {
        this.mirrored.set(val)
        this.wrapperEl?.style.setProperty('--solar-icon-mirrored', val ? 'scale(-1, 1)' : 'none')
    }
}

export function useSolar(): SolarService {
    return inject(SolarService)
}

@Component({
    selector: 'solar-provider',
    template: `<div #wrapper><ng-content /></div>`,
    standalone: true,
    providers: [SolarService],
})
export class SolarProviderComponent {
    readonly color = input<string>()
    readonly size = input<string | number>()
    readonly strokeWidth = input<number>()
    readonly duotoneColor = input<string>()
    readonly duotoneOpacity = input<number>()
    readonly mirrored = input<boolean>()

    private readonly wrapperRef = viewChild<ElementRef<HTMLDivElement>>('wrapper')
    private readonly solarService = inject(SolarService)

    constructor() {
        effect(() => {
            const el = this.wrapperRef()?.nativeElement
            if (el) this.solarService.registerWrapper(el)
        })

        effect(() => {
            const c = this.color()
            const el = this.wrapperRef()?.nativeElement
            if (c != null) {
                this.solarService.color.set(c)
                el?.style.setProperty('--solar-icon-color', c)
            }
        })

        effect(() => {
            const s = this.size()
            const el = this.wrapperRef()?.nativeElement
            if (s != null) {
                this.solarService.size.set(s)
                el?.style.setProperty('--solar-icon-size', typeof s === 'number' ? `${s}px` : s)
            }
        })

        effect(() => {
            const sw = this.strokeWidth()
            const el = this.wrapperRef()?.nativeElement
            if (sw != null) {
                this.solarService.strokeWidth.set(sw)
                el?.style.setProperty('--solar-stroke-width', String(sw))
            }
        })

        effect(() => {
            const dc = this.duotoneColor()
            const el = this.wrapperRef()?.nativeElement
            if (dc) {
                this.solarService.duotoneColor.set(dc)
                el?.style.setProperty('--solar-duotone-color', dc)
            }
        })

        effect(() => {
            const d = this.duotoneOpacity()
            const el = this.wrapperRef()?.nativeElement
            if (d != null) {
                this.solarService.duotoneOpacity.set(d)
                el?.style.setProperty('--solar-duotone-opacity', String(d))
            }
        })

        effect(() => {
            const m = this.mirrored()
            const el = this.wrapperRef()?.nativeElement
            if (m !== undefined) {
                this.solarService.mirrored.set(m)
                el?.style.setProperty('--solar-icon-mirrored', m ? 'scale(-1, 1)' : 'none')
            }
        })
    }
}

// packages/svelte/src/lib/SolarProvider.svelte
<script lang="ts">
    import { setContext } from 'svelte';
    import type { Snippet } from 'svelte';
    import { SOLAR_CONTEXT_KEY } from './useSolar';

    interface Props {
        color?: string;
        size?: string | number;
        strokeWidth?: number;
        duotoneColor?: string;
        duotoneOpacity?: number;
        mirrored?: boolean;
        children: Snippet;
    }

    let {
        color = $bindable(),
        size = $bindable(),
        strokeWidth = $bindable(),
        duotoneColor = $bindable(),
        duotoneOpacity = $bindable(),
        mirrored = $bindable(),
        children,
    }: Props = $props();

    let wrapperEl: HTMLDivElement | undefined;

    const setColor = (val: string) => (color = val);
    const setSize = (val: string | number) => (size = val);
    const setStrokeWidth = (val: number) => (strokeWidth = val);
    const setDuotoneColor = (val: string) => (duotoneColor = val);
    const setDuotoneOpacity = (val: number) => (duotoneOpacity = val);
    const setMirrored = (val: boolean) => (mirrored = val);

    const state = {
        get color() {
            return color;
        },
        setColor,
        get size() {
            return size;
        },
        setSize,
        get strokeWidth() {
            return strokeWidth;
        },
        setStrokeWidth,
        get duotoneColor() {
            return duotoneColor;
        },
        setDuotoneColor,
        get duotoneOpacity() {
            return duotoneOpacity;
        },
        setDuotoneOpacity,
        get mirrored() {
            return mirrored;
        },
        setMirrored,
    };

    setContext(SOLAR_CONTEXT_KEY, state);

    $effect(() => {
        if (color != null) wrapperEl?.style.setProperty('--solar-icon-color', String(color));
    });

    $effect(() => {
        if (size != null)
            wrapperEl?.style.setProperty(
                '--solar-icon-size',
                typeof size === 'number' ? `${size}px` : String(size)
            );
    });

    $effect(() => {
        if (strokeWidth != null)
            wrapperEl?.style.setProperty('--solar-stroke-width', String(strokeWidth));
    });

    $effect(() => {
        if (duotoneColor) wrapperEl?.style.setProperty('--solar-duotone-color', duotoneColor);
    });

    $effect(() => {
        if (duotoneOpacity != null)
            wrapperEl?.style.setProperty('--solar-duotone-opacity', String(duotoneOpacity));
    });

    $effect(() => {
        if (mirrored !== undefined)
            wrapperEl?.style.setProperty(
                '--solar-icon-mirrored',
                mirrored ? 'scale(-1, 1)' : 'none'
            );
    });
</script>

<div bind:this={wrapperEl}>
    {@render children()}
</div>
